language: elixir
matrix:
  include:
  - otp_release: 18.3
    elixir: 1.4.0
  - otp_release: 18.3
    elixir: 1.5.1
  - otp_release: 19.2
    elixir: 1.4.0
  - otp_release: 19.2
    elixir: 1.5.1
  - otp_release: 20.0
    elixir: 1.5.1
script:
- MIX_ENV=test mix do deps.get, test && mix credo && mix coveralls.travis
after_script:
- mix deps.get --only docs
- MIX_ENV=docs mix inch.report
deploy:
  api_key:
    secure: PkqfHD1lGBTm4tQt6hPQFML6crp8u6cd7tnKNyv2wOjyjvAlUm/3qtNlQw+NChEmy/1r/D7Tx/70SrYUUl/93klm4koGQVncq81WAiYGe83W9VEMoXnnyJl4tAxPVGQs2QvaQJFjJs3aygCSkumxNhdHiEHFRruA5qeOHFUyZStyywri04gTw4s6TFYSv+DaqpPRFheu2nHBpQyeffFuic1t+tska4wMb5BIx8EKSnD0VFHNzOsQ6acvzpQAqxhp1KELCQOzg31D+1xKcQXV5NXbVw1AULJFgmILslnC5I1blRpGXTxYKJgOmDvztnqJMTmlTvvuNWTOtu2jzL/EJcay6FWZxX8gI4gMqBa4ry1g32fK0li8BPHY9ZG0c0gWv/IW4mwCJJjWLgmHzGgBWHEcS4da/EdDNi5SlcrY/4+V63yYAqFKnpbcK2R1UhXRJOeVzblFkp+QzqC4zOMGlMTMxxNdc1wcKLpspGjwWHJxah/1UiTUB+w8+iC/28LqTBH89Ik0VjfJjdeg1l4od57P3G59bmxRrq+UW4xiCTdpXHRMjqRQPIIrZt6liJUTbSUAhWrp2e1zPpDLXOvkvssMXr+nInRiXtVEc6XXUA8Amb/jqw7uODFA844EdRcvoLlAY8MeV0I+1ZTooiNZHo7akrkcDzgpa2sVv0o7jSc=
