language: elixir
matrix:
  include:
  - otp_release: 18.3
    elixir: 1.5.1
script:
- MIX_ENV=test mix do deps.get, test && mix credo
after_script:
- mix deps.get --only docs
- MIX_ENV=docs mix inch.report
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: Szpv8aDr/MSPaR81JEJmbR6BucGT0xTTH2u8ALoKNFyDLCGqka+zTyP8smS8aUlzKXy/uSifs37cs1WHneTU/DnN4w7SKVMbZtny1xkDmHH2N4Yy3/Rpfs5bqZlzeSOzizzFZoFggpWuZlmCckXgzxV7JrnBb50ZQi409/BbYkZQXLBOX8mznQ+htN9yHjkfqyRYWENYzgCZspoVtpsm6B6YSLZDXQmHf0CK6tFP/Aa7xlVCcM2B3QhJ+ZkD8TREYXgxDiWqAOUtFx/9JgquUsCZtGvByS0RaLrjXvU+0M0wGSM6BfcAaOB4HOml67I8+zrr/ZinQkKHtGpL5R7iAvD1FBGJ578bt+yGoWk+hvd2f0TuSsRM6VsJW7QV9qTg0yWxX+GrGMAHWPpzzXbtQ7eARXUPpDZMFGllYYv3HPODhRNvOyRKeaDzHFbmyI7THhIIkfw/43tSmGko42PzSbdKSYqyzj0/zpXXxfyJIOJeU4cvBN7mnsAhzFsT07gDf6trpCOer40crFAn1jlg+rdQp00myG7jk5QJa101cRC8fbjAgC3b9T3j/oRxgVmpMLS52Qlpvh2zWq1Yo5dAhkqFb2LHceO2FgTQYk8amwDghGLqIQv9Uw5eKyGTLRPEcq5Z6nqTwA77ErSRelpgvBI0GX8qopSlkDlDZCoce9U=
